# Generated by Django 4.1.3 on 2022-11-30 08:58

import apps.base.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.base.services.get_upload_path_album, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), apps.base.services.validate_image_size], verbose_name='Album Cover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.SlugField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('track', models.FileField(upload_to=apps.base.services.get_upload_path_track, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='Track')),
                ('slug', models.SlugField(blank=True, max_length=220, primary_key=True, serialize=False, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='track_images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album')),
                ('genre', models.ManyToManyField(related_name='genre', to='music.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='TrackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='track_images')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='music.track')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('tracks', models.ManyToManyField(related_name='play_list_tracks', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
