# Generated by Django 4.1.3 on 2022-12-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='music',
            new_name='track',
        ),
    ]
