# Generated by Django 4.1.3 on 2022-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlist_tracks', to='music.track'),
        ),
    ]
