# Generated by Django 4.1.3 on 2022-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
