# Generated by Django 4.1.3 on 2022-12-06 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to='track', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='Track'),
        ),
    ]
