# Generated by Django 4.1.3 on 2022-12-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_plays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='plays',
        ),
    ]
