# Generated by Django 4.1.3 on 2022-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_track_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
    ]
